## Practical Machine Learning - Coursera Course Project

### Background

Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset).

### Data

The training data for this project are available here:

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv

The test data are available here:

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv

The data for this project come from this source: http://groupware.les.inf.puc-rio.br/har. If you use the document you create for this class for any purpose please cite them as they have been very generous in allowing their data to be used for this kind of assignment.


## Project Report

### Data Loading & Cleaning

First we need to load all the libraries we will be using in our code and set seed as follows

    library(caret)
    library(randomForest)
    library(rattle)
    library(rpart)
    library(rpart.plot)
    set.seed(123)
Data Loading

    train_csv <- read.csv("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv")
    test_csv <- read.csv("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv")

Check dimensions

    dim(train_csv)
    dim(test_csv)
    
    [1] 19622   160
    [1]  20 160
    
Data Cleaning

Removing all the columns with missing values

    train_csv_clean <- train_csv[,colSums(is.na(train_csv)) == 0]
    test_csv_clean <- test_csv[,colSums(is.na(test_csv)) == 0]

Again checking the dimensions

    dim(train_csv_clean)
    dim(test_csv_clean)

    [1] 19622    93
    [1] 20 60

Deleting variables which are irrelevant and not important in predicting the output

    train_csv_final_clean <- train_csv_clean[,-c(1:7)]
    test_csv_final_clean <- test_csv_clean[,-c(1:7)]
    x<-names(train_csv_final_clean) %in% c("skewness_roll_belt", "skewness_roll_belt.1", "skewness_yaw_belt",
    "max_yaw_belt", "kurtosis_picth_dumbbell", "kurtosis_yaw_dumbbell", "skewness_roll_dumbbell",
    "skewness_pitch_dumbbell", "skewness_yaw_dumbbell", "max_yaw_dumbbell", "min_yaw_dumbbell",
    "amplitude_yaw_dumbbell", "kurtosis_roll_forearm", "kurtosis_picth_forearm", "kurtosis_yaw_forearm",
    "skewness_roll_forearm", "skewness_pitch_forearm", "skewness_yaw_forearm", "max_roll_forearm",
    "max_yaw_forearm", "min_roll_forearm", "min_yaw_belt", "amplitude_yaw_belt", "avg_roll_arm", "stddev_roll_arm",
    "var_roll_arm", "avg_pitch_arm", "stddev_pitch_arm", "var_pitch_arm", "avg_yaw_arm",
    "stddev_yaw_arm", "avg_roll_forearm", "stddev_roll_forearm", "var_roll_forearm",
    "avg_pitch_forearm", "stddev_pitch_forearm", "var_pitch_forearm", "avg_yaw_forearm",
    "stddev_yaw_forearm", "var_yaw_forearm", "var_yaw_arm", "kurtosis_roll_arm", "kurtosis_picth_arm",
    "kurtosis_yaw_arm", "skewness_roll_arm", "skewness_pitch_arm", "skewness_yaw_arm",
    "max_roll_arm", "min_roll_arm", "kurtosis_roll_belt", "kurtosis_picth_belt",
    "kurtosis_yaw_belt", "min_pitch_arm", "amplitude_roll_arm", "amplitude_pitch_arm",
    "kurtosis_roll_dumbbell", "min_yaw_forearm", "amplitude_roll_forearm",
    "amplitude_yaw_forearm")
    train_csv_final_clean<-train_csv_final_clean[!x]


### Data Partioning

Partioning the data into 60% training set and 40% test set as follows

    trainer<- createDataPartition(y=train_csv_final_clean$classe, p=0.60, list=FALSE)
    final_train<- train_csv_final_clean[trainer, ]
    final_test<- train_csv_final_clean[-trainer, ]

### Applying Prediction Algorithms
We will be using two prediction models namely the Random Forest Model and the Decision Tree Model as follows

Random forest

    model <- randomForest(classe ~., data=final_train, method="class")
    predict_model <- predict(model, final_test, type = "class")
    confusionMatrix(predict_model, final_test$classe)

Output of the Confusion Matrix for Random Forest

    Confusion Matrix and Statistics

              Reference
    Prediction    A    B    C    D    E
             A 2229    9    0    0    0
             B    3 1506   11    0    0
             C    0    3 1355   11    3
             D    0    0    2 1275    2
             E    0    0    0    0 1437

    Overall Statistics
                                          
                   Accuracy : 0.9944          
                     95% CI : (0.9925, 0.9959)
        No Information Rate : 0.2845          
        P-Value [Acc > NIR] : < 2.2e-16       
                                          
                      Kappa : 0.9929          
     Mcnemar's Test P-Value : NA              

    Statistics by Class:

                         Class: A Class: B Class: C Class: D Class: E
    Sensitivity            0.9987   0.9921   0.9905   0.9914   0.9965
    Specificity            0.9984   0.9978   0.9974   0.9994   1.0000
    Pos Pred Value         0.9960   0.9908   0.9876   0.9969   1.0000
    Neg Pred Value         0.9995   0.9981   0.9980   0.9983   0.9992
    Prevalence             0.2845   0.1935   0.1744   0.1639   0.1838
    Detection Rate         0.2841   0.1919   0.1727   0.1625   0.1832
    Detection Prevalence   0.2852   0.1937   0.1749   0.1630   0.1832
    Balanced Accuracy      0.9985   0.9949   0.9939   0.9954   0.9983

Decision Trees

    model1<- rpart(classe ~ ., data=final_train, method="class")
    predict_model1<- predict(model1, final_test, type = "class")
    confusionMatrix(predict_model1, final_test$classe)

Output of the Confusion Matrix for the Decision trees

    Confusion Matrix and Statistics

              Reference
    Prediction    A    B    C    D    E
             A 2059  203   18  128   79
             B   60 1086  211   70   93
             C   20   83  998  184   83
             D   71  138   81  863  120
             E   22    8   60   41 1067

    Overall Statistics
                                          
                   Accuracy : 0.774           
                     95% CI : (0.7646, 0.7832)
        No Information Rate : 0.2845          
        P-Value [Acc > NIR] : < 2.2e-16       
                                          
                      Kappa : 0.713           
     Mcnemar's Test P-Value : < 2.2e-16       

    Statistics by Class:

                         Class: A Class: B Class: C Class: D Class: E
    Sensitivity            0.9225   0.7154   0.7295   0.6711   0.7399
    Specificity            0.9238   0.9314   0.9429   0.9375   0.9795
    Pos Pred Value         0.8279   0.7145   0.7295   0.6779   0.8907
    Neg Pred Value         0.9677   0.9317   0.9429   0.9356   0.9436
    Prevalence             0.2845   0.1935   0.1744   0.1639   0.1838
    Detection Rate         0.2624   0.1387   0.1744   0.1622   0.1527
    Balanced Accuracy      0.9231   0.8234   0.1272   0.1100   0.1360
    Detection Prevalence   0.3170   0.1934   0.8362   0.8043   0.8597

The Random Forest Algorithm gives us better accuracy of 0.9944 compared to the Decision Trees Algorithm whose accuracy is just 0.774 thus for prediction we will be using the Random Forest Algorithm.

### Prediction and Output File Generation

Prediction using Random Forest Algorithm as follows

    final_prediction <- predict(model, test_csv, type = "class")
    print(final_prediction)

Output of Final Prediction

    1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 
    B  A  B  A  A  E  D  B  A  A  B  C  B  A  E  E  A  B  B  B 
    Levels: A B C D E

Writing Prediction Output to Files

    pmlwrite = function(temp){
    n = length(temp)
    for(i in 1:n){
      filename = paste0("problem-id_",i,".txt")
      write.table(temp[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
     }
    }
    pmlwrite(final_prediction)



